//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface Const extends Operand, Element{
    Element getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_GlobalRef(GlobalRef globalRef);
        T case_Nullpointer(Nullpointer nullpointer);
        T case_Sizeof(Sizeof sizeof);
        T case_ConstInt(ConstInt constInt);
        T case_ConstStruct(ConstStruct constStruct);
        T case_ProcedureRef(ProcedureRef procedureRef);
        T case_ConstBool(ConstBool constBool);
    }

    public interface MatcherVoid {
        void case_GlobalRef(GlobalRef globalRef);
        void case_Nullpointer(Nullpointer nullpointer);
        void case_Sizeof(Sizeof sizeof);
        void case_ConstInt(ConstInt constInt);
        void case_ConstStruct(ConstStruct constStruct);
        void case_ProcedureRef(ProcedureRef procedureRef);
        void case_ConstBool(ConstBool constBool);
    }

    Const copy();
    Const copyWithRefs();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
