//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJImplements extends NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_ImplementsInterfaceList(NQJImplementsInterfaceList implementsInterfaceList);
        T case_ImplementsNothing(NQJImplementsNothing implementsNothing);
    }

    public interface MatcherVoid {
        void case_ImplementsInterfaceList(NQJImplementsInterfaceList implementsInterfaceList);
        void case_ImplementsNothing(NQJImplementsNothing implementsNothing);
    }

    NQJImplements copy();
    NQJImplements copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
