//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJInterfaceFunctionDecl extends NQJElement {
    void setReturnType(NQJType returnType);
    NQJType getReturnType();
    void setName(String name);
    String getName();
    void setFormalParameters(NQJVarDeclList formalParameters);
    NQJVarDeclList getFormalParameters();
    NQJElement getParent();
    NQJInterfaceFunctionDecl copy();
    NQJInterfaceFunctionDecl copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
