//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJImplementsInterfaceList extends AsgList<NQJImplementsInterface> implements NQJImplements, NQJElement{
    public NQJImplementsInterfaceList copy() {
        NQJImplementsInterfaceList result = new NQJImplementsInterfaceListImpl();
        for (NQJImplementsInterface elem : this) {
            result.add((NQJImplementsInterface) elem.copy());
        }
        return result;
    }

    @Override public NQJImplementsInterfaceList copyWithRefs() {
        NQJImplementsInterfaceList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
