//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

@SuppressWarnings({"cast", "unused", "rawtypes"})
public abstract class NQJInterfaceFunctionDeclList extends AsgList<NQJInterfaceFunctionDecl> implements NQJElement{
    public NQJInterfaceFunctionDeclList copy() {
        NQJInterfaceFunctionDeclList result = new NQJInterfaceFunctionDeclListImpl();
        for (NQJInterfaceFunctionDecl elem : this) {
            result.add((NQJInterfaceFunctionDecl) elem.copy());
        }
        return result;
    }

    @Override public NQJInterfaceFunctionDeclList copyWithRefs() {
        NQJInterfaceFunctionDeclList res = copy();
        return res;
    }

    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
