//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJInterfaceDecl extends NQJTopLevelDecl, NQJElement {
    void setName(String name);
    String getName();
    void setFuncs(NQJInterfaceFunctionDeclList funcs);
    NQJInterfaceFunctionDeclList getFuncs();
    NQJElement getParent();
    NQJInterfaceDecl copy();
    NQJInterfaceDecl copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
