//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJImplementsInterface extends NQJElement {
    void setName(String name);
    String getName();
    NQJElement getParent();
    NQJImplementsInterface copy();
    NQJImplementsInterface copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
