//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJMemberDecl extends NQJElement{
    void setName(String name);
    String getName();
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_FunctionDecl(NQJFunctionDecl functionDecl);
        T case_VarDecl(NQJVarDecl varDecl);
    }

    public interface MatcherVoid {
        void case_FunctionDecl(NQJFunctionDecl functionDecl);
        void case_VarDecl(NQJVarDecl varDecl);
    }

    NQJMemberDecl copy();
    NQJMemberDecl copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
}
