//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJTypeClass extends NQJBaseType, NQJElement {
    void setName(String name);
    String getName();
    NQJElement getParent();
    NQJTypeClass copy();
    NQJTypeClass copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract NQJClassDecl getClassDeclaration();
    /** null*/
    public abstract void setClassDeclaration(NQJClassDecl classDeclaration);
    /** null*/
    public abstract analysis.Type getType();
    /** null*/
    public abstract void setType(analysis.Type type);
}
